# Generated by Django 3.1.2 on 2020-10-09 13:38

from django.db import migrations, models
import django.utils.datetime_safe


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20201009_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default=django.utils.datetime_safe.date.today),
        ),
    ]
