# Generated by Django 3.1.2 on 2020-10-09 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20201009_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='pub_date',
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='/cover/default.jpg', upload_to='cover/'),
        ),
    ]
