# Generated by Django 3.1.2 on 2020-10-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20201009_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default='/authors/default.jpg', upload_to='authors/'),
        ),
    ]
